import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import { ThemeProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";
import SessionProviderComp from "@/components/nextauth/SessionProvider";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { useMessages } from "next-intl";
import QueryProvider from "@/components/utils/QueryProvider";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homely - A Real Estate Framer Template",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  session,
  params,
}: Readonly<{
  children: React.ReactNode;
  session: any;
  params: { locale: string };
}>) {
  const messages = (await import(`../../../messages/${params.locale}.json`))
    .default;
  if (!messages) return notFound();

  // Determine direction based on locale
  const dir = params.locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={params.locale} dir={dir}>
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <QueryProvider>
          <NextTopLoader color="#07be8a" />
          <SessionProviderComp session={session}>
            <ThemeProvider
              attribute="class"
              enableSystem={true}
              defaultTheme="light"
            >
              <NextIntlClientProvider
                locale={params.locale}
                messages={messages}
              >
                <Header />
                {children}
                <Footer />
              </NextIntlClientProvider>
            </ThemeProvider>
          </SessionProviderComp>
        </QueryProvider>
      </body>
    </html>
  );
}
